spring:
  datasource:
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    validation-query: SELECT 1
    url: jdbc:postgresql://localhost:5432/mydatabase
  flyway:
    enabled: true
    locations:
      classpath: /db/migration
    validate-on-migrate: true
    baseline-on-migrate: false
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    sql-migration-separator: __
    sql-migration-suffixes: .sql
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      timeout: 2000ms

springdoc:
  swagger-ui:
    path: /docs
    tagsSorter: alpha
    operationsSorter: alpha
  api-docs:
    path: /docs/json
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
